-- Isolated staging fixtures. All changes, including temporary active org, roll back.
begin;
do $$
declare o uuid:=gen_random_uuid(); other_org uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); d uuid:=gen_random_uuid(); sa uuid; regular uuid; assigned uuid; denied boolean;
begin
 select id into sa from public.profiles where role='super_admin' limit 1;
 select id into regular from public.profiles where role<>'super_admin' limit 1;
 assert sa is not null and regular is not null, 'Missing staging test users';
 insert into public.organizations(id,name) values(o,'TEST linked super admin'),(other_org,'TEST other org');
 update public.profiles set organization_id=o where id=sa;
 insert into public.user_organizations(organization_id,user_id,role) values(o,regular,'admin');
 insert into public.boards(id,name,organization_id) values(b,'TEST assignment',o);
 insert into public.deals(id,title,organization_id,board_id) values(d,'TEST existing lead',o,b);
 assert not private.team_is_org_member(o,sa), 'Visiting admin became member';
 assert private.team_is_org_member(o,regular), 'Regular member lost eligibility';
 denied:=false;
 begin perform public.team_manage(o,sa,'master',jsonb_build_object('userId',sa)); exception when raise_exception then denied:=true; end;
 assert denied,'Visiting admin became master';
 perform set_config('request.jwt.claim.sub',sa::text,true);
 set local role authenticated;
 denied:=false;
 begin update public.deals set owner_id=sa where id=d; exception when insufficient_privilege then denied:=true; end;
 assert denied,'Visiting admin assigned owner';
 reset role;
 perform set_config('request.jwt.claim.sub','',true);
 insert into public.user_organizations(organization_id,user_id,role) values(o,sa,'admin');
 assert private.team_is_org_member(o,sa),'Explicit member rejected';
 assert not private.team_is_org_member(other_org,sa),'Membership leaked to other org';
 perform set_config('request.jwt.claim.sub',sa::text,true);
 set local role authenticated;
 update public.deals set owner_id=sa where id=d;
 assert (select owner_id=sa from public.deals where id=d),'Manual assignment failed';
 reset role;
 perform set_config('request.jwt.claim.sub','',true);
 perform public.team_manage(o,sa,'master',jsonb_build_object('userId',sa));
 assert (select master_user_id=sa from public.org_team_settings where organization_id=o),'Master not set';
 assert (select role='super_admin' from public.profiles where id=sa),'Global role downgraded';
 perform public.team_manage(o,sa,'master',jsonb_build_object('userId',regular));
 perform public.team_manage(o,sa,'assign',jsonb_build_object('userId',sa,'kind','vendedor','roleId',null));
 assert (select role='super_admin' from public.profiles where id=sa),'Local role change downgraded global role';
 insert into public.organization_settings(organization_id,lead_distribution_enabled,lead_distribution_manual) values(o,true,true)
 on conflict(organization_id) do update set lead_distribution_enabled=true,lead_distribution_manual=true;
 insert into public.lead_distribution(organization_id,user_id,weight,active) values(o,sa,100,true);
 insert into public.deals(title,organization_id,board_id) values('TEST automatic',o,b) returning owner_id into assigned;
 assert assigned=sa,'Automatic distribution ignored linked super admin';
 perform set_config('request.jwt.claim.sub',sa::text,true);
 set local role authenticated;
 insert into public.deals(title,organization_id,board_id) values('TEST manual distribution',o,b) returning owner_id into assigned;
 assert assigned=sa,'Manual distribution failed';
 reset role;
 perform set_config('request.jwt.claim.sub','',true);
 insert into public.deals(title,organization_id,board_id,owner_id) values('TEST explicit owner',o,b,regular) returning owner_id into assigned;
 assert assigned=regular,'Distribution replaced explicit owner';
 insert into public.lead_distribution_boards(organization_id,user_id,board_id,active) values(o,sa,b,false);
 insert into public.deals(title,organization_id,board_id) values('TEST disabled pipeline',o,b) returning owner_id into assigned;
 assert assigned is null,'Disabled pipeline received lead';
 delete from public.lead_distribution_boards where organization_id=o;
 delete from public.user_organizations where organization_id=o and user_id=sa;
 insert into public.deals(title,organization_id,board_id) values('TEST removed member',o,b) returning owner_id into assigned;
 assert assigned is null,'Removed membership still received lead';
 assert not has_function_privilege('authenticated','private.team_is_org_member(uuid,uuid)','EXECUTE'),'Membership helper exposed';
end $$;
rollback;
