-- Run in the staging SQL console / CLI. Everything is rolled back.
begin;
do $$
declare
 o uuid:=gen_random_uuid(); b1 uuid:=gen_random_uuid(); b2 uuid:=gen_random_uuid();
 s1 uuid:=gen_random_uuid(); s2 uuid:=gen_random_uuid(); r uuid:=gen_random_uuid();
 d1 uuid:=gen_random_uuid(); d2 uuid:=gen_random_uuid(); d3 uuid:=gen_random_uuid();
 c1 uuid:=gen_random_uuid(); c2 uuid:=gen_random_uuid(); created_contact uuid;
 u uuid; other_user uuid; sa uuid; n integer; denied boolean;
begin
 select id into u from public.profiles where role <> 'super_admin' limit 1;
 select id into other_user from public.profiles where role <> 'super_admin' and id<>u limit 1;
 select id into sa from public.profiles where role='super_admin' limit 1;
 if u is null or other_user is null or sa is null then raise exception 'Fixtures require two members and a technical admin'; end if;
 insert into public.organizations(id,name) values(o,'TEST team roles - rollback');
 insert into public.user_organizations(organization_id,user_id,role) values(o,u,'vendedor'),(o,other_user,'admin');
 insert into public.boards(id,name,organization_id) values(b1,'Allowed test funnel',o),(b2,'Hidden test funnel',o);
 insert into public.board_stages(id,name,"order",board_id,organization_id) values(s1,'A',0,b1,o),(s2,'B',1,b1,o);
 insert into public.team_roles(id,organization_id,name,boards) values(r,o,'Own leads',jsonb_build_array(jsonb_build_object('boardId',b1,'scope','own','create',true,'edit',false,'move',true,'delete',false)));
 insert into public.team_role_assignments(organization_id,user_id,role_id) values(o,u,r);
 insert into public.contacts(id,name,organization_id) values(c1,'Visible test contact',o),(c2,'Hidden test contact',o);
 insert into public.deals(id,title,organization_id,board_id,stage_id,owner_id,contact_id) values
 (d1,'Own',o,b1,s1,u,c1),(d2,'Unassigned',o,b1,s1,null,c2),(d3,'Hidden funnel',o,b2,null,u,null);
 if exists(select 1 from public.org_team_settings where organization_id=o and master_user_id is not null) then raise exception 'Unexpected automatic master'; end if;
 denied:=false;
 begin perform public.team_manage(o,other_user,'master',jsonb_build_object('userId',u)); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Ordinary admin assigned master'; end if;
 perform set_config('request.jwt.claim.sub',u::text,true);
 set local role authenticated;
 select count(*) into n from public.deals where organization_id=o;
 if n<>1 then raise exception 'Own visibility expected 1, got %',n; end if;
 select count(*) into n from public.contacts where organization_id=o;
 if n<>1 then raise exception 'Contacts leaked: %',n; end if;
 select count(*) into n from public.boards where organization_id=o;
 if n<>1 then raise exception 'Funnel visibility failed: %',n; end if;
 denied:=false;
 begin update public.deals set title='Forbidden edit' where id=d1; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Edit without permission succeeded'; end if;
 update public.deals set stage_id=s2,status=s2::text where id=d1;
 if not exists(select 1 from public.deals where id=d1 and stage_id=s2) then raise exception 'Move without edit should succeed'; end if;
 denied:=false;
 begin update public.deals set stage_id=s1,title='Smuggled edit' where id=d1; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Combined move bypassed edit'; end if;
 denied:=false;
 begin update public.deals set owner_id=null where id=d1; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Ownership bypass'; end if;
 denied:=false;
 begin delete from public.deals where id=d1; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Delete without permission succeeded'; end if;
 denied:=false;
 begin insert into public.deals(title,organization_id,board_id,owner_id) values('Forbidden funnel',o,b2,u); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Created lead in forbidden funnel'; end if;
 denied:=false;
 begin perform public.team_manage(o,sa,'master',jsonb_build_object('userId',u)); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Authenticated client spoofed service actor'; end if;
 insert into public.contacts(name,organization_id) values('New contact',o) returning id into created_contact;
 if created_contact is null then raise exception 'Contact creation returning failed'; end if;
 insert into public.deals(title,organization_id,board_id,stage_id,contact_id) values('Created own lead',o,b1,s1,created_contact);
 if not exists(select 1 from public.deals where contact_id=created_contact and owner_id=u) then raise exception 'Own create did not assign creator'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub','',true);
 update public.team_roles set boards=jsonb_set(boards,'{0,scope}','"all"') where id=r;
 perform set_config('request.jwt.claim.sub',u::text,true);
 set local role authenticated;
 select count(*) into n from public.deals where organization_id=o;
 if n<>3 then raise exception 'All should include unassigned only in allowed funnel: %',n; end if;
 reset role;
 perform set_config('request.jwt.claim.sub','',true);
 delete from public.team_role_assignments where organization_id=o and user_id=u;
 perform set_config('request.jwt.claim.sub',u::text,true);
 set local role authenticated;
 select count(*) into n from public.deals where organization_id=o;
 if n<>0 then raise exception 'Missing assignment did not deny'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub','',true);
 perform public.team_manage(o,sa,'master',jsonb_build_object('userId',u));
 if not (public.team_effective_access(o,u)->>'canManage')::boolean then raise exception 'Master cannot manage'; end if;
 denied:=false;
 begin perform public.team_manage(o,u,'master',jsonb_build_object('userId',other_user)); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Master transferred own title'; end if;
 denied:=false;
 begin delete from public.user_organizations where organization_id=o and user_id=u; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Removed current master'; end if;
 perform public.team_manage(o,sa,'master',jsonb_build_object('userId',other_user));
 if (public.team_effective_access(o,u)->>'canManage')::boolean then raise exception 'Former master retained management'; end if;
 if not (public.team_effective_access(o,u)->>'fullAccess')::boolean then raise exception 'Former master lost admin operation access'; end if;
 perform set_config('request.jwt.claim.sub',u::text,true);
 set local role authenticated;
 select count(*) into n from public.deals where organization_id=o;
 if n<>4 then raise exception 'Admin does not see all funnels: %',n; end if;
 reset role;
 perform set_config('request.jwt.claim.sub','',true);
end $$;
select 'team_roles: all database assertions passed (rollback)' as result;
rollback;
