-- Staging-only; creates no messages, enables no bots; every fixture rolls back.
BEGIN;
CREATE TEMP TABLE label_test_results(test text, passed boolean);
DO $$
DECLARE org uuid:='428e1830-2ff5-425a-b9b1-f9379897c2c6'; other_org uuid; cid uuid; d1 uuid; d2 uuid; foreign_deal uuid;
 c1 uuid; c2 uuid; local_chat uuid; grp uuid; a uuid; b uuid; x uuid; foreign_label uuid; original text[];
 prefix text:='regression-'||gen_random_uuid()::text||'-';
BEGIN
 SELECT id INTO other_org FROM public.organizations WHERE id<>org LIMIT 1;
 IF other_org IS NULL THEN RAISE EXCEPTION 'Two staging organizations required'; END IF;
 INSERT INTO public.contacts(organization_id,name) VALUES(org,prefix||'contact') RETURNING id INTO cid;
 INSERT INTO public.deals(organization_id,title,contact_id,tags) VALUES(org,prefix||'one',cid,ARRAY[prefix||'A']) RETURNING id INTO d1;
 INSERT INTO public.deals(organization_id,title,contact_id,tags) VALUES(org,prefix||'two',cid,ARRAY[prefix||'other-lead']) RETURNING id INTO d2;
 INSERT INTO public.deals(organization_id,title,tags) VALUES(other_org,prefix||'foreign','{}') RETURNING id INTO foreign_deal;
 SELECT id INTO a FROM public.wa_labels WHERE organization_id=org AND name=prefix||'A';
 -- Direct legacy catalog compatibility, including CSS color and normalized duplicate.
 INSERT INTO public.tags(organization_id,name,color) VALUES(org,' '||prefix||'B ','bg-purple-500') RETURNING id INTO b;
 IF NOT EXISTS(SELECT 1 FROM public.wa_labels WHERE id=b AND name=prefix||'B' AND color='purple') THEN RAISE EXCEPTION 'Legacy insert not canonical'; END IF;
 BEGIN INSERT INTO public.tags(organization_id,name) VALUES(org,upper(prefix||'B')); RAISE EXCEPTION 'Duplicate accepted'; EXCEPTION WHEN unique_violation THEN NULL; END;
 INSERT INTO public.wa_labels(organization_id,name) VALUES(other_org,prefix||'A') RETURNING id INTO foreign_label;
 INSERT INTO label_test_results VALUES('catalog legacy insert/color and same-org normalized uniqueness',true);
 INSERT INTO public.wa_conversations(organization_id,wa_phone,contact_id,deal_id,label_ids) VALUES(org,'test-'||gen_random_uuid(),cid,d1,ARRAY[b]) RETURNING id INTO c1;
 INSERT INTO public.wa_conversations(organization_id,wa_phone,contact_id,deal_id) VALUES(org,'test-'||gen_random_uuid(),cid,d1) RETURNING id INTO c2;
 IF NOT (SELECT tags @> ARRAY[prefix||'A',prefix||'B'] FROM public.deals WHERE id=d1) THEN RAISE EXCEPTION 'Link did not union'; END IF;
 IF (SELECT label_ids FROM public.wa_conversations WHERE id=c1) IS DISTINCT FROM (SELECT label_ids FROM public.wa_conversations WHERE id=c2) THEN RAISE EXCEPTION 'Fanout missing'; END IF;
 IF (SELECT tags FROM public.deals WHERE id=d2)<>ARRAY[prefix||'other-lead'] THEN RAISE EXCEPTION 'Other contact lead contaminated'; END IF;
 INSERT INTO label_test_results VALUES('link union, multiple conversations, other contact lead untouched',true);
 UPDATE public.wa_conversations SET label_ids=array_remove(label_ids,a) WHERE id=c1;
 IF (SELECT tags @> ARRAY[prefix||'A'] FROM public.deals WHERE id=d1) OR (SELECT a=ANY(label_ids) FROM public.wa_conversations WHERE id=c2) THEN RAISE EXCEPTION 'Chat removal not propagated'; END IF;
 UPDATE public.deals SET tags=tags||ARRAY[prefix||'A'] WHERE id=d1;
 IF NOT (SELECT a=ANY(label_ids) FROM public.wa_conversations WHERE id=c1) THEN RAISE EXCEPTION 'Lead addition not propagated'; END IF;
 UPDATE public.deals SET tags=array_remove(tags,prefix||'B') WHERE id=d1;
 IF (SELECT b=ANY(label_ids) FROM public.wa_conversations WHERE id=c2) THEN RAISE EXCEPTION 'Lead removal not propagated'; END IF;
 PERFORM public.mutate_conversation_labels(org,c1,ARRAY[b],ARRAY[a]);
 IF (SELECT tags FROM public.deals WHERE id=d1)<>ARRAY[prefix||'B'] THEN RAISE EXCEPTION 'Atomic delta failed'; END IF;
 INSERT INTO label_test_results VALUES('add/remove from either origin and atomic delta',true);
 BEGIN PERFORM public.mutate_conversation_labels(org,c1,ARRAY[a],'{}',d2,true); RAISE EXCEPTION 'Changed link accepted after authorization'; EXCEPTION WHEN serialization_failure THEN NULL; END;
 BEGIN PERFORM public.mutate_conversation_labels(org,c1,ARRAY[a],'{}',NULL,true); RAISE EXCEPTION 'Concurrent link from unlinked state accepted'; EXCEPTION WHEN serialization_failure THEN NULL; END;
 IF (SELECT tags FROM public.deals WHERE id=d1)<>ARRAY[prefix||'B'] THEN RAISE EXCEPTION 'Rejected mutation modified linked lead'; END IF;
 PERFORM public.mutate_conversation_labels(org,c1,ARRAY[b],'{}',d1,true);
 INSERT INTO label_test_results VALUES('atomic labels require the exact authorized link including null',true);
 INSERT INTO public.wa_conversations(organization_id,wa_phone,label_ids) VALUES(org,'test-'||gen_random_uuid(),ARRAY[a]) RETURNING id INTO local_chat;
 INSERT INTO public.wa_conversations(organization_id,wa_phone,is_group,label_ids) VALUES(org,'test-'||gen_random_uuid(),true,ARRAY[a]) RETURNING id INTO grp;
 UPDATE public.wa_conversations SET deal_id=d1 WHERE id=local_chat;
 IF NOT (SELECT tags @> ARRAY[prefix||'A',prefix||'B'] FROM public.deals WHERE id=d1) THEN RAISE EXCEPTION 'Late link lost labels'; END IF;
 SELECT tags INTO original FROM public.deals WHERE id=d1;
 UPDATE public.wa_conversations SET deal_id=d2 WHERE id=local_chat;
 IF (SELECT tags FROM public.deals WHERE id=d1) IS DISTINCT FROM original THEN RAISE EXCEPTION 'Relink changed previous lead'; END IF;
 UPDATE public.wa_conversations SET deal_id=NULL,label_ids='{}' WHERE id=local_chat;
 IF NOT (SELECT tags @> ARRAY[prefix||'A'] FROM public.deals WHERE id=d2) THEN RAISE EXCEPTION 'Unlink changed old lead'; END IF;
 UPDATE public.wa_conversations SET label_ids='{}' WHERE id=grp;
 IF (SELECT tags FROM public.deals WHERE id=d1) IS DISTINCT FROM original THEN RAISE EXCEPTION 'Group propagated'; END IF;
 INSERT INTO label_test_results VALUES('late link, relink/unlink preserves previous lead, group independence',true);
 BEGIN UPDATE public.wa_conversations SET deal_id=foreign_deal WHERE id=c1; RAISE EXCEPTION 'Foreign lead accepted'; EXCEPTION WHEN check_violation THEN NULL; END;
 BEGIN UPDATE public.wa_conversations SET label_ids=ARRAY[foreign_label] WHERE id=c1; RAISE EXCEPTION 'Foreign label accepted'; EXCEPTION WHEN check_violation THEN NULL; END;
 BEGIN UPDATE public.wa_conversations SET deal_id=d1 WHERE id=grp; RAISE EXCEPTION 'Group link accepted'; EXCEPTION WHEN check_violation THEN NULL; END;
 INSERT INTO label_test_results VALUES('cross-org label/lead and group links rejected',true);
 UPDATE public.tags SET name=prefix||'Renamed' WHERE id=b;
 IF NOT (SELECT tags @> ARRAY[prefix||'Renamed'] FROM public.deals WHERE id=d1) THEN RAISE EXCEPTION 'Rename missing'; END IF;
 UPDATE public.deals SET tags=tags||ARRAY[prefix||'B'] WHERE id=d1;
 IF EXISTS(SELECT 1 FROM public.wa_labels WHERE organization_id=org AND name=prefix||'B') THEN RAISE EXCEPTION 'Stale rename resurrected'; END IF;
 DELETE FROM public.tags WHERE id=b;
 UPDATE public.deals SET tags=tags||ARRAY[prefix||'Renamed'] WHERE id=d1;
 IF EXISTS(SELECT 1 FROM public.wa_labels WHERE organization_id=org AND name=prefix||'Renamed') THEN RAISE EXCEPTION 'Stale deletion resurrected'; END IF;
 IF EXISTS(SELECT 1 FROM public.wa_conversations WHERE organization_id=org AND b=ANY(label_ids)) THEN RAISE EXCEPTION 'Deleted ID remains'; END IF;
 INSERT INTO public.tags(organization_id,name) VALUES(org,prefix||'Renamed') RETURNING id INTO x;
 UPDATE public.deals SET tags=tags||ARRAY[prefix||'Renamed'] WHERE id=d1;
 IF NOT (SELECT x=ANY(label_ids) FROM public.wa_conversations WHERE id=c1) THEN RAISE EXCEPTION 'Explicit recreate not usable'; END IF;
 INSERT INTO label_test_results VALUES('rename/delete tombstones and explicit recreation',true);
 IF has_function_privilege('authenticated','public.mutate_conversation_labels(uuid,uuid,uuid[],uuid[],uuid,boolean)','execute') OR has_function_privilege('anon','public.mutate_conversation_labels(uuid,uuid,uuid[],uuid[],uuid,boolean)','execute') THEN RAISE EXCEPTION 'RPC exposed'; END IF;
 INSERT INTO label_test_results VALUES('backend atomic RPC is not public',true);
 BEGIN UPDATE public.deals SET organization_id=other_org WHERE id=d1; RAISE EXCEPTION 'Linked lead moved organization'; EXCEPTION WHEN check_violation THEN NULL; END;
 UPDATE public.deals SET deleted_at=now() WHERE id=d1;
 IF EXISTS(SELECT 1 FROM public.wa_conversations WHERE deal_id=d1) THEN RAISE EXCEPTION 'Deleted lead retained active links'; END IF;
 INSERT INTO label_test_results VALUES('linked lead cannot cross org; soft deletion unlinks without removing labels',true);
END $$;
SELECT * FROM label_test_results;
ROLLBACK;
